config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :locations

  resources :todos, shallow: true do
    resources :tasks
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :user
  belongs_to :todo
  
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :todos
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @locations = Location.all
    @todos = Todo.all
    @tasks = Task.all
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.user = current_user
    @location.save
    redirect_to '/'
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to '/'
  end

end

def location_params
  params.require(:location).permit(:name)
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @todo = Todo.find(params[:todo_id])
    @task = Task.new
  end

  def create
    @todo = Todo.find(params[:todo_id])
    @task = @todo.tasks.new(params.require(:task).permit(:task))
    @task.user = current_user
    @task.save
    redirect_to '/'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to '/'
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = current_user
    @todo.save
    redirect_to '/'
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    flash[:notice] = 'Todo list deleted successefully'
    redirect_to '/'
  end

end

  def todo_params
    params.require(:todo).permit(:name)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
<ul class='nav nav-pills nav-justified'>
  <li role='presentation'>
    <a href='/locations/new'>Add location</a>
  </li>
  <li role='presentation'>
    <a href='/todos/new'>Add To Do list</a>
  </li>
</ul>

  <div class="container-fluid">
    <div class="row">
      <% if @locations.any? %>
        <% @locations.each do |location| %>
          <% if current_user.id == location.user_id %>
          <div class="col-md-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="panel-title">Weather for <%= location.name %></div>
                <div class ='panel-close'>
                  <%= link_to 'Remove location', location_path(location), method: :delete %>
                </div>
              </div>
              <div class="panel-body">
                <% barometer = Barometer.new(location.name) %>
                <% weather = barometer.measure %>
                <p>Current Temp: <%= weather.current.temperature.c %></p>
                <p>Tomorrow High: <%= weather.tomorrow.high.c %></p>
                <p>Tomorrow Low: <%= weather.tomorrow.low.c %></p>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
      <% if @todos.any? %>
        <% @todos.each do |todo| %>
        <% if current_user.id == todo.user_id %>
          <div class="col-md-6">
            <div class="panel panel-success">
              <div class="panel-heading">
                <div class="panel-title"><%= todo.name %></div>
                <div class ='panel-close'>
                  <%= link_to 'X', todo_path(todo), method: :delete %>
                </div>
              </div>
              <div class="panel-body">
                <% if @tasks.any? %>
                  <% @tasks.each do |task| %>
                  <ul>
                    <li><%= task.task %> [<%= link_to "Task done!", task_path(task), method: :delete %>]</li>
                  </ul>
                  <% end %>
                <% end %>
                <%= link_to "Add task", new_todo_task_path(todo) %>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class='alert alert-info' role='alert'>
    <h1>Sign in to see your dashboard!</h1>
  </div>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Cats!</h3>
        </div>
        <div class="panel-body">
          <a href="http://thecatapi.com"><img src="http://thecatapi.com/api/images/get?format=src&type=gif" class='cats'></a>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Puppies!</h3>
        </div>
        <div class="panel-body">
          <a href="http://thepuppyapi.com"><img src="http://www.thepuppyapi.com/puppy?format=src" class='puppies'></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboardy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <!-- <p class='notice'><%= notice %></p>
  <p class='alert'><%= alert %></p> -->

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Dashboardy</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>


<%= yield %>


</body>
</html>

app/views/locations/new.html.erb
<h2>Add a location:</h2>

<%= form_for @location do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit "Add location" %>

<% end %>

app/views/tasks/new.html.erb
<h2>Add a task:</h2>

<%= form_for [@todo, @task] do |f| %>

<%= f.label :task %>
<%= f.text_field :task %>

<%= f.submit "Add task" %>

<% end %>

app/views/todos/new.html.erb
<h2>Add a To Do list:</h2>

<%= form_for @todo do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.submit "Create list" %>

<% end %>